### ISSUE TITLE
SELECT AS STRUCT should be used to avoid error "Subquery of type IN must have only one output column"

### ISSUE THREAD

**Issue by jdimatteo** [googleapis/python-bigquery-sqlalchemy#457]
See discussion at https://stackoverflow.com/questions/72130273/sqlalchemy-select-as-struct-to-resolve-error-subquery-of-type-in-must-have-only

#### Environment details

  - OS type and version: Debian Linux
  - Python version: 3.9.10
  - pip version: 21.3.1
  - `sqlalchemy-bigquery` version: 1.4.3

#### Steps to reproduce

  1. Run an update with in subquery clause with multiple columns, like full code example below
  
  ```
      conn.execute(
            data.update().
                 where(sqlalchemy.tuple_(data.c.person_id, data.c.person_name).
                       not_in(sqlalchemy.sql.select(people.c.id, people.c.name))).
                 values(invalid=True))
  ```

#### Code example

While this code results in the below stack trace, note that this code works with sqlite, which can be enabled by commenting out the corresponding engine line.

```python
#!/usr/bin/env python3

import sqlalchemy  # pip install SQLAlchemy==1.4.27

import sqlalchemy_bigquery
 
# engine = sqlalchemy.create_engine('sqlite://')
engine = sqlalchemy.create_engine('bigquery://jdimatteo-v/scratch')  # pip install sqlalchemy-bigquery==1.4.3
metadata_obj = sqlalchemy.MetaData()
people = sqlalchemy.Table(
    'people', metadata_obj,
    sqlalchemy.Column('id', sqlalchemy.Integer),
    sqlalchemy.Column('name', sqlalchemy.String),
)
data = sqlalchemy.Table(
    'data', metadata_obj,
    sqlalchemy.Column('person_id', sqlalchemy.Integer),
    sqlalchemy.Column('person_name', sqlalchemy.String),
    sqlalchemy.Column('data_foo', sqlalchemy.String),
    sqlalchemy.Column('invalid', sqlalchemy.Boolean),
)
metadata_obj.create_all(engine)
conn = engine.connect()

def create_records():
    conn.execute(people.delete().where(True == True))
    conn.execute(people.insert().values(id=1, name='Mary'))
    conn.execute(people.insert().values(id=2, name='James'))

    conn.execute(data.delete().where(True == True))
    conn.execute(data.insert().values(person_id=1, person_name='Mary', data_foo='good foo', invalid=None))
    conn.execute(data.insert().values(person_id=42, person_name='Bob', data_foo='chop suey', invalid=None))
    conn.execute(data.insert().values(person_id=1, person_name='James', data_foo='mixed up', invalid=None))

def dynamic_update():
    conn.execute(
            data.update().
                 where(sqlalchemy.tuple_(data.c.person_id, data.c.person_name).
                       not_in(sqlalchemy.sql.select(people.c.id, people.c.name))).
                 values(invalid=True))

def print_records(msg):
    print(f'{msg}:')
    print("  people:")
    for person in conn.execute(sqlalchemy.sql.select(people)):
        print('    ', person)
    print("  data:")
    for datum in conn.execute(sqlalchemy.sql.select(data)):
        print('    ', datum)
    print()

create_records()
print_records('initial values')
dynamic_update()
print_records('after update')
```

This update statement does work with BigQuery through `SELECT AS STRUCT` -- how can I use SQLAlchemy to express this?

This *does* work:

```
UPDATE `jdimatteo-v.scratch.data`
   SET `invalid`=True
 WHERE (person_id, person_name)
       NOT IN (SELECT AS STRUCT id, name
                 FROM `jdimatteo-v.scratch.people`
              )
```

#### Stack trace

```
Traceback (most recent call last):
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 203, in _execute
    self._query_job.result()
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Subquery of type IN must have only one output column at [1:98]

Location: US
Job ID: b4112e06-35f0-4232-9bdf-37db83237ac6


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 494, in with_closed_check
    return method(self, *args, **kwargs)
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 166, in execute
    self._execute(
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 205, in _execute
    raise exceptions.DatabaseError(exc)
google.cloud.bigquery.dbapi.exceptions.DatabaseError: 400 Subquery of type IN must have only one output column at [1:98]

Location: US
Job ID: b4112e06-35f0-4232-9bdf-37db83237ac6


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/test.py", line 54, in <module>
    dynamic_update()
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/test.py", line 36, in dynamic_update
    conn.execute(
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 494, in with_closed_check
    return method(self, *args, **kwargs)
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 166, in execute
    self._execute(
  File "/home/jdimatteo/gunk/sqlalchemy_update_with_select/venv/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 205, in _execute
    raise exceptions.DatabaseError(exc)
sqlalchemy.exc.DatabaseError: (google.cloud.bigquery.dbapi.exceptions.DatabaseError) 400 Subquery of type IN must have only one output column at [1:98]

Location: US
Job ID: b4112e06-35f0-4232-9bdf-37db83237ac6

[SQL: UPDATE `data` SET `invalid`=%(invalid:BOOL)s WHERE ((`data`.`person_id`, `data`.`person_name`) NOT IN (SELECT `people`.`id`, `people`.`name` 
FROM `people`))]
[parameters: {'invalid': True}]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```

**Comment by r1b** [comment]
@jdimatteo For your workaround, try using [prefix_with](https://docs.sqlalchemy.org/en/20/core/selectable.html#sqlalchemy.sql.expression.Select.prefix_with):

```
>>> print(sa.select(sa.column("foo")).prefix_with("AS STRUCT"))
SELECT AS STRUCT foo
```

**Comment by chalmerlowe** [comment]
In light of other priorities and backlog and the presence of what appears to be a usable workaround, gonna close this as "Will not fix"
