### ISSUE TITLE
Migration support for nullable/non-nullable arrays during migration

### ISSUE THREAD

**Issue by leo-schick** [googleapis/python-bigquery-sqlalchemy#460]
It looks like the property `nullable` in a column with type of ARRAY is not properly taken care of:

When I have an array column defined as `primary_key=True` or `nullable=False` the sqlalchemy engine creates a migration which causes a `400 NOT NULL cannot be applied to ARRAY field 'node_path'. NULL arrays are always stored as an empty array.` exception in BigQuery.

### Sample Model

``` python 
class FileDependency(Base):
    """A combined hash of the content of a list of files"""
    __tablename__ = 'data_integration_file_dependency'

    node_path = sqlalchemy.Column(sqlalchemy.ARRAY(sqlalchemy.TEXT), primary_key=True)
    dependency_type = sqlalchemy.Column(sqlalchemy.String, primary_key=True)
    hash = sqlalchemy.Column(sqlalchemy.String)
    timestamp = sqlalchemy.Column(sqlalchemy.TIMESTAMP(timezone=True))
```

This creates the following migration SQL code

``` sql
CREATE TABLE `data_integration_file_dependency` (
    `node_path` ARRAY<STRING> NOT NULL, 
    `dependency_type` STRING NOT NULL, 
    `hash` STRING, 
    `timestamp` TIMESTAMP
);
```
which then causes the following exception:
``` 
Traceback (most recent call last):
  File "/srv/git/leo-schick/test-mara-google-app/env/lib/python3.7/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 203, in _execute
    self._query_job.result()
  File "/srv/git/leo-schick/test-mara-google-app/env/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/srv/git/leo-schick/test-mara-google-app/env/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/srv/git/leo-schick/test-mara-google-app/env/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/srv/git/leo-schick/test-mara-google-app/env/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/srv/git/leo-schick/test-mara-google-app/env/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/srv/git/leo-schick/test-mara-google-app/env/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 NOT NULL cannot be applied to ARRAY field 'node_path'. NULL arrays are always stored as an empty array.

Location: europe-west3
Job ID: 23348b7c-54e3-4a40-8005-bc0bfcd0c1d7
```

Let us leave the fact behind that primary keys are not supported in BigQuery: In my opinion the migration should not generate `<column name> ARRAY<...> NOT NULL` column in the `CREATE TABLE` statement, because this is not supported. It should then maybe automatiaclly set internally `nullable=True` so that the `NOT NULL` hint is not used.

P.S. Would be interesting to know why someone from the BigQuery team thought it would make sence to enforce this error. A solution could be as well that a `NOT NULL` hint behind an ARRAY field is just ignored (= optimistic behavior). Since the array is always empty, this shounds more like a typical NOT NULL column instead of a NULL-able column.

#### Environment details

  - OS type and version: linux debian
  - Python version: `Python 3.7.3`
  - pip version: `pip 22.1.1`
  - `sqlalchemy-bigquery` version: `sqlalchemy-bigquery==1.4.3`

**Comment by chalmerlowe** [comment]
This is an issue with the BigQuery backend, not this Python library, specifically. For example, this behavior occurs in the GUI and is the expected behavior. 

Closing as will not fix.
