### ISSUE TITLE
ModuleNotFoundError for `pytz` when selecting timestamp fields.

### ISSUE THREAD

**Issue by edelooff** [googleapis/python-bigquery-sqlalchemy#475]
#### Environment details

  - OS type and version: Debian 11 (from docker `python:3.9-slim`)
  - Python version: `3.9.13`
  - pip version: `22.0.4`
  - `sqlalchemy-bigquery` version: `1.4.4`

#### Steps to reproduce

  1. Create a fresh virtualenv, docker container or whatnot with just `sqlalchemy-bigquery==1.4.4` installed
  2. Connect to BigQuery using `create_engine`
  3. Perform a query that retrieves a timestamp and fetch the result set

#### Code example

```python
from sqlalchemy import create_engine

engine = create_engine("bigquery://{GCP_PROJECT_ID}")
result = engine.execute("SELECT CURRENT_TIMESTAMP()").fetchall()
```

#### Stack trace
```
Traceback (most recent call last):
  File "/workdir/reproduction.py", line 4, in <module>
    result = engine.execute("SELECT CURRENT_TIMESTAMP()").fetchall()
  File "/workdir/.pip/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1014, in fetchall
    return self._allrows()
  File "/workdir/.pip/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 400, in _allrows
    rows = self._fetchall_impl()
  File "/workdir/.pip/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 1803, in _fetchall_impl
    return self.cursor_strategy.fetchall(self, self.cursor)
  File "/workdir/.pip/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 981, in fetchall
    self.handle_exception(result, dbapi_cursor, e)
  File "/workdir/.pip/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 941, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/workdir/.pip/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2030, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/workdir/.pip/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/workdir/.pip/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 977, in fetchall
    rows = dbapi_cursor.fetchall()
  File "/workdir/.pip/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 494, in with_closed_check
    return method(self, *args, **kwargs)
  File "/workdir/.pip/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 383, in fetchall
    return list(self._query_data)
  File "/workdir/.pip/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 480, in <genexpr>
    return (to_table_row(row_data) for row_data in rows_iterable)
  File "/workdir/.pip/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 476, in to_table_row
    values = tuple(value.as_py() for value in row.values())
  File "/workdir/.pip/lib/python3.9/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 476, in <genexpr>
    values = tuple(value.as_py() for value in row.values())
  File "pyarrow/scalar.pxi", line 465, in pyarrow.lib.TimestampScalar.as_py
  File "pyarrow/types.pxi", line 2002, in pyarrow.lib.string_to_tzinfo
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
ModuleNotFoundError: No module named 'pytz'
```

The installed version of `pyarrow` is `6.0.1` (specifically `pyarrow-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`), which may itself be part of the problem. I've not checked to see if newer version of that library resolve the problem.

Including a requirement for a (any?) version of `pytz` in `sqlalchemy-bigquery` would resolve the immediate impact.

**Comment by chalmerlowe** [comment]
I created a new virtual environment and installed only `Python=3.9` and `sqlalchemy-bigquery`.
The test code noted above ran flawlessly.
During the virtualenv creation and package installation, I noted that `pytz` was automatically installed.

**Comment by edelooff** [comment]
That is incredibly odd. When I create a new virtualenv, install `sqlalchemy-bigquery` into it and run the script above, it still fails on exactly the same error. For completeness I'll provide the entire terminal session below (with a few newlines included for clarity):

```
elmer@Hopper:~/devel/play$ python -m venv tmp
elmer@Hopper:~/devel/play$ source tmp/bin/activate

(tmp) elmer@Hopper:~/devel/play$ pip install sqlalchemy-bigquery
Collecting sqlalchemy-bigquery
  Using cached sqlalchemy_bigquery-1.4.4-py2.py3-none-any.whl (32 kB)
Collecting sqlalchemy<=1.4.27,>=1.2.0
  Using cached SQLAlchemy-1.4.27-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
  Preparing metadata (setup.py) ... done
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Using cached google_api_core-2.10.2-py3-none-any.whl (115 kB)
Collecting google-cloud-bigquery-storage<3.0.0dev,>=2.0.0
  Using cached google_cloud_bigquery_storage-2.16.2-py2.py3-none-any.whl (185 kB)
Collecting pyarrow<7.0dev,>=3.0.0
  Using cached pyarrow-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25.6 MB)
Collecting google-auth<3.0.0dev,>=1.25.0
  Using cached google_auth-2.12.0-py2.py3-none-any.whl (169 kB)
Collecting google-cloud-bigquery<4.0.0dev,>=2.25.2
  Using cached google_cloud_bigquery-3.3.5-py2.py3-none-any.whl (211 kB)
Collecting googleapis-common-protos<2.0dev,>=1.56.2
  Using cached googleapis_common_protos-1.56.4-py2.py3-none-any.whl (211 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5
  Using cached protobuf-4.21.7-cp37-abi3-manylinux2014_x86_64.whl (408 kB)
Collecting requests<3.0.0dev,>=2.18.0
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting six>=1.9.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting grpcio<2.0dev,>=1.47.0
  Using cached grpcio-1.49.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
Collecting google-resumable-media<3.0dev,>=0.6.0
  Using cached google_resumable_media-2.4.0-py2.py3-none-any.whl (77 kB)
Collecting google-cloud-core<3.0.0dev,>=1.4.1
  Using cached google_cloud_core-2.3.2-py2.py3-none-any.whl (29 kB)
Collecting python-dateutil<3.0dev,>=2.7.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting packaging<22.0.0dev,>=14.3
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting proto-plus<2.0.0dev,>=1.22.0
  Using cached proto_plus-1.22.1-py3-none-any.whl (47 kB)
Collecting numpy>=1.16.6
  Using cached numpy-1.23.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Collecting greenlet!=0.4.17
  Using cached greenlet-1.1.3.post0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (156 kB)
Collecting grpcio-status<2.0dev,>=1.33.2
  Using cached grpcio_status-1.49.1-py3-none-any.whl (14 kB)
Collecting google-crc32c<2.0dev,>=1.0
  Using cached google_crc32c-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (32 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
Installing collected packages: pyasn1, urllib3, six, rsa, pyparsing, pyasn1-modules, protobuf, numpy, idna, greenlet, google-crc32c, future, charset-normalizer, certifi, cachetools, sqlalchemy, requests, python-dateutil, pyarrow, proto-plus, packaging, grpcio, googleapis-common-protos, google-resumable-media, google-auth, grpcio-status, google-api-core, google-cloud-core, google-cloud-bigquery-storage, google-cloud-bigquery, sqlalchemy-bigquery
  Running setup.py install for future ... done
Successfully installed cachetools-5.2.0 certifi-2022.9.24 charset-normalizer-2.1.1 future-0.18.2 google-api-core-2.10.2 google-auth-2.12.0 google-cloud-bigquery-3.3.5 google-cloud-bigquery-storage-2.16.2 google-cloud-core-2.3.2 google-crc32c-1.5.0 google-resumable-media-2.4.0 googleapis-common-protos-1.56.4 greenlet-1.1.3.post0 grpcio-1.49.1 grpcio-status-1.49.1 idna-3.4 numpy-1.23.4 packaging-21.3 proto-plus-1.22.1 protobuf-4.21.7 pyarrow-6.0.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyparsing-3.0.9 python-dateutil-2.8.2 requests-2.28.1 rsa-4.9 six-1.16.0 sqlalchemy-1.4.27 sqlalchemy-bigquery-1.4.4 urllib3-1.26.12

(tmp) elmer@Hopper:~/devel/play$ python
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlalchemy import create_engine
>>> engine = create_engine("bigquery://{GCP_PROJECT_ID}")
>>> engine.execute("SELECT CURRENT_TIMESTAMP()").fetchall()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1014, in fetchall
    return self._allrows()
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 400, in _allrows
    rows = self._fetchall_impl()
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 1803, in _fetchall_impl
    return self.cursor_strategy.fetchall(self, self.cursor)
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 981, in fetchall
    self.handle_exception(result, dbapi_cursor, e)
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 941, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2030, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 977, in fetchall
    rows = dbapi_cursor.fetchall()
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 494, in with_closed_check
    return method(self, *args, **kwargs)
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 383, in fetchall
    return list(self._query_data)
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 480, in <genexpr>
    return (to_table_row(row_data) for row_data in rows_iterable)
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 476, in to_table_row
    values = tuple(value.as_py() for value in row.values())
  File "/home/elmer/devel/play/tmp/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 476, in <genexpr>
    values = tuple(value.as_py() for value in row.values())
  File "pyarrow/scalar.pxi", line 465, in pyarrow.lib.TimestampScalar.as_py
  File "pyarrow/types.pxi", line 2002, in pyarrow.lib.string_to_tzinfo
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
ModuleNotFoundError: No module named 'pytz'
```

**Comment by chalmerlowe** [comment]
I installed the libraries, etc using conda/mamba. I had no errors in running the code.
Based on your comment, I also tried to install using venv and pip. I had the same error you had. 
Gonna re-open this issue. 
Sadness.
