### ISSUE TITLE
Structs don't compile if the key is a reserved keyword

### ISSUE THREAD

**Issue by ravirahman** [googleapis/python-bigquery-sqlalchemy#850]
If a struct field contains a reserved keyword, it doesn't compile

#### Environment details
  - `sqlalchemy-bigquery` version: 1.6.1

#### Stack trace
```
[SQL: 
CREATE TABLE IF NOT EXISTS `feat_e7f05092575006a5fd31700c9f73eb543ae55fbab6a48b8d595bf4dc2c` (
	value STRUCT<group STRING, category STRING>
)
(Background on this error at: https://sqlalche.me/e/14/4xp6)
Traceback (most recent call last):
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 203, in _execute
    self._query_job.result()
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected keyword GROUP at [5:22]

Location: US
Job ID: 17bf10a2-3578-4558-87bc-72facf8a6b98


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/_helpers.py", line 494, in with_closed_check
    return method(self, *args, **kwargs)
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 166, in execute
    self._execute(
  File "/Users/r_rahman/venvs/chalk/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 205, in _execute
    raise exceptions.DatabaseError(exc)
google.cloud.bigquery.dbapi.exceptions.DatabaseError: 400 Syntax error: Unexpected keyword GROUP at [5:22]

```

**Comment by chalmerlowe** [comment]
Thanks for offering up the linked PR (#851) for consideration.
You are correct in that if a user has a value in a STRUCT that is a SQL keyword that term must be "protected" or "escaped" using backticks (`).

The approach offered in the PR breaks our existing tests because the tests are not expecting to see the STRUCT values encapsulated in backticks.

I have not tried this PR against a live Bigquery instance to see how adding backticks to every value might negatively impact the processing OR results.

Especially one with pre-existing column names, etc.

For now, in light of other priorities and limitations on our current staffing and the fact that the majority of our clients do not seem to be affected by this limitation at this time, I am gonna close this issue and the associated PR.

**Comment by pykenny** [comment]
For regular queries it should be okay in most cases for not quoting when referencing `STRUCT` fields. However, this behavior can break DDLs when users manage their schema in codebase through SQLAlchemy/Alembic:

Try creating a model and defines a `STRUCT` column using BigQuery keyword as field name:

```python
class MyModel(Base):
    __tablename__ = "my_table"
    uid = Column(Integer, primary_key=True)
    payload = Column(STRUCT(record_id=String, start=DateTime, end=DateTime, count=Integer))
```

Then generate table creation statement on this model through [CreateTable](https://docs.sqlalchemy.org/en/14/core/ddl.html#sqlalchemy.schema.CreateTable) or Alembic revision-autogenerate + dry run, and you'll get:
```sql
CREATE TABLE `my_table` (
	`uid` INT64 NOT NULL,
	`payload` STRUCT<record_id STRING, start DATETIME, end DATETIME, count INT64>
)
```

Which will cause BigQuery service to complain about incorrect syntax:

```text
Syntax error: Unexpected keyword END ...
```

Feel comfortable to swap "end" in the above case with other GoogleSQL keywords such as "from", "to", etc..
